services:
  tailsocks:
    build: .
    image: tailsocks
    hostname: ${TS_HOSTNAME:-tailsocks}
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./statedir:/var/lib/tailscale/
    ports:
      - "${TS_HOST:-127.0.0.1}:${TS_PORT:-8888}:1080"
